/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "embotelladora.h"

/*! \file Implementation of the state machine 'embotelladora'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_main_region_Inicio_default(Embotelladora* handle);
static void enseq_main_region_Movimiento_default(Embotelladora* handle);
static void enseq_main_region_Llenando_default(Embotelladora* handle);
static void enseq_main_region_Retirar_Botella_default(Embotelladora* handle);
static void enseq_main_region_default(Embotelladora* handle);
static void exseq_main_region_Inicio(Embotelladora* handle);
static void exseq_main_region_Movimiento(Embotelladora* handle);
static void exseq_main_region_Llenando(Embotelladora* handle);
static void exseq_main_region_Retirar_Botella(Embotelladora* handle);
static void exseq_main_region(Embotelladora* handle);
static void react_main_region__entry_Default(Embotelladora* handle);

/*! State machine reactions. */
static sc_integer react(Embotelladora* handle, const sc_integer transitioned_before);

/*! The reactions of state Inicio. */
static sc_integer main_region_Inicio_react(Embotelladora* handle, const sc_integer transitioned_before);

/*! The reactions of state Movimiento. */
static sc_integer main_region_Movimiento_react(Embotelladora* handle, const sc_integer transitioned_before);

/*! The reactions of state Llenando. */
static sc_integer main_region_Llenando_react(Embotelladora* handle, const sc_integer transitioned_before);

/*! The reactions of state Retirar Botella. */
static sc_integer main_region_Retirar_Botella_react(Embotelladora* handle, const sc_integer transitioned_before);


static void clear_in_events(Embotelladora* handle);

static void micro_step(Embotelladora* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Embotelladora* handle);



static void embotelladora_eventqueue_init(embotelladora_eventqueue * eq, embotelladora_event *buffer, sc_integer capacity);
static sc_integer embotelladora_eventqueue_size(embotelladora_eventqueue * eq);
static void embotelladora_event_init(embotelladora_event * ev, EmbotelladoraEventID name);
static embotelladora_event embotelladora_eventqueue_pop(embotelladora_eventqueue * eq);
static sc_boolean embotelladora_eventqueue_push(embotelladora_eventqueue * eq, embotelladora_event ev);
static void embotelladora_add_event_to_queue(embotelladora_eventqueue * eq, EmbotelladoraEventID name);
static void embotelladora_dispatch_event(Embotelladora* handle, const embotelladora_event * event);
static embotelladora_event embotelladora_get_next_event(Embotelladora* handle);
static void embotelladora_dispatch_next_event(Embotelladora* handle);


void embotelladora_init(Embotelladora* handle)
{
	sc_integer i;
	
	for (i = 0; i < EMBOTELLADORA_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Embotelladora_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart embotelladora */
	handle->iface.T_valvula = bool_false;
	handle->iface.M_cinta = bool_false;
	
	handle->isExecuting = bool_false;
	embotelladora_eventqueue_init(&handle->in_event_queue, handle->in_buffer, EMBOTELLADORA_IN_EVENTQUEUE_BUFFERSIZE);
}

void embotelladora_enter(Embotelladora* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart embotelladora */
	enseq_main_region_default(handle);
	do
	{ 
		handle->stateConfVectorChanged = bool_false;
		micro_step(handle);
	} while (handle->stateConfVectorChanged == bool_true);
	handle->isExecuting = bool_false;
}

void embotelladora_exit(Embotelladora* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart embotelladora */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean embotelladora_is_active(const Embotelladora* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < EMBOTELLADORA_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Embotelladora_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean embotelladora_is_final(const Embotelladora* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean embotelladora_is_state_active(const Embotelladora* handle, EmbotelladoraStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Embotelladora_main_region_Inicio :
			result = (sc_boolean) (handle->stateConfVector[SCVI_EMBOTELLADORA_MAIN_REGION_INICIO] == Embotelladora_main_region_Inicio
			);
			break;
		case Embotelladora_main_region_Movimiento :
			result = (sc_boolean) (handle->stateConfVector[SCVI_EMBOTELLADORA_MAIN_REGION_MOVIMIENTO] == Embotelladora_main_region_Movimiento
			);
			break;
		case Embotelladora_main_region_Llenando :
			result = (sc_boolean) (handle->stateConfVector[SCVI_EMBOTELLADORA_MAIN_REGION_LLENANDO] == Embotelladora_main_region_Llenando
			);
			break;
		case Embotelladora_main_region_Retirar_Botella :
			result = (sc_boolean) (handle->stateConfVector[SCVI_EMBOTELLADORA_MAIN_REGION_RETIRAR_BOTELLA] == Embotelladora_main_region_Retirar_Botella
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clear_in_events(Embotelladora* handle)
{
	handle->iface.sensorG_ON_raised = bool_false;
	handle->iface.sensorG_OFF_raised = bool_false;
	handle->iface.sensorC_ON_raised = bool_false;
}

static void micro_step(Embotelladora* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Embotelladora_main_region_Inicio :
		{
			main_region_Inicio_react(handle, -1);
			break;
		}
		case Embotelladora_main_region_Movimiento :
		{
			main_region_Movimiento_react(handle, -1);
			break;
		}
		case Embotelladora_main_region_Llenando :
		{
			main_region_Llenando_react(handle, -1);
			break;
		}
		case Embotelladora_main_region_Retirar_Botella :
		{
			main_region_Retirar_Botella_react(handle, -1);
			break;
		}
		default: break;
	}
}

static void run_cycle(Embotelladora* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	embotelladora_dispatch_next_event(handle);
	do
	{ 
		do
		{ 
			handle->stateConfVectorChanged = bool_false;
			micro_step(handle);
		} while (handle->stateConfVectorChanged == bool_true);
		clear_in_events(handle);
		embotelladora_dispatch_next_event(handle);
	} while (((handle->iface.sensorG_ON_raised == bool_true) || (handle->iface.sensorG_OFF_raised == bool_true)) || (handle->iface.sensorC_ON_raised == bool_true));
	handle->isExecuting = bool_false;
}


void embotelladora_raise_sensorG_ON(Embotelladora* handle)
{
	embotelladora_add_event_to_queue(&(handle->in_event_queue), Embotelladora_sensorG_ON);
	run_cycle(handle);
}

void embotelladora_raise_sensorG_OFF(Embotelladora* handle)
{
	embotelladora_add_event_to_queue(&(handle->in_event_queue), Embotelladora_sensorG_OFF);
	run_cycle(handle);
}

void embotelladora_raise_sensorC_ON(Embotelladora* handle)
{
	embotelladora_add_event_to_queue(&(handle->in_event_queue), Embotelladora_sensorC_ON);
	run_cycle(handle);
}



sc_boolean embotelladora_get_t_valvula(const Embotelladora* handle)
{
	return handle->iface.T_valvula;
}
sc_boolean embotelladora_get_m_cinta(const Embotelladora* handle)
{
	return handle->iface.M_cinta;
}

/* implementations of all internal functions */

/* 'default' enter sequence for state Inicio */
static void enseq_main_region_Inicio_default(Embotelladora* handle)
{
	/* 'default' enter sequence for state Inicio */
	handle->stateConfVector[0] = Embotelladora_main_region_Inicio;
	handle->stateConfVectorChanged = bool_true;
}

/* 'default' enter sequence for state Movimiento */
static void enseq_main_region_Movimiento_default(Embotelladora* handle)
{
	/* 'default' enter sequence for state Movimiento */
	handle->stateConfVector[0] = Embotelladora_main_region_Movimiento;
	handle->stateConfVectorChanged = bool_true;
}

/* 'default' enter sequence for state Llenando */
static void enseq_main_region_Llenando_default(Embotelladora* handle)
{
	/* 'default' enter sequence for state Llenando */
	handle->stateConfVector[0] = Embotelladora_main_region_Llenando;
	handle->stateConfVectorChanged = bool_true;
}

/* 'default' enter sequence for state Retirar Botella */
static void enseq_main_region_Retirar_Botella_default(Embotelladora* handle)
{
	/* 'default' enter sequence for state Retirar Botella */
	handle->stateConfVector[0] = Embotelladora_main_region_Retirar_Botella;
	handle->stateConfVectorChanged = bool_true;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Embotelladora* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state Inicio */
static void exseq_main_region_Inicio(Embotelladora* handle)
{
	/* Default exit sequence for state Inicio */
	handle->stateConfVector[0] = Embotelladora_last_state;
}

/* Default exit sequence for state Movimiento */
static void exseq_main_region_Movimiento(Embotelladora* handle)
{
	/* Default exit sequence for state Movimiento */
	handle->stateConfVector[0] = Embotelladora_last_state;
}

/* Default exit sequence for state Llenando */
static void exseq_main_region_Llenando(Embotelladora* handle)
{
	/* Default exit sequence for state Llenando */
	handle->stateConfVector[0] = Embotelladora_last_state;
}

/* Default exit sequence for state Retirar Botella */
static void exseq_main_region_Retirar_Botella(Embotelladora* handle)
{
	/* Default exit sequence for state Retirar Botella */
	handle->stateConfVector[0] = Embotelladora_last_state;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Embotelladora* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of embotelladora.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Embotelladora_main_region_Inicio :
		{
			exseq_main_region_Inicio(handle);
			break;
		}
		case Embotelladora_main_region_Movimiento :
		{
			exseq_main_region_Movimiento(handle);
			break;
		}
		case Embotelladora_main_region_Llenando :
		{
			exseq_main_region_Llenando(handle);
			break;
		}
		case Embotelladora_main_region_Retirar_Botella :
		{
			exseq_main_region_Retirar_Botella(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Embotelladora* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Inicio_default(handle);
}


static sc_integer react(Embotelladora* handle, const sc_integer transitioned_before)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return transitioned_before;
}

static sc_integer main_region_Inicio_react(Embotelladora* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Inicio. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorG_OFF_raised == bool_true)
		{ 
			exseq_main_region_Inicio(handle);
			enseq_main_region_Movimiento_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		}  else
		{
			if (handle->iface.sensorG_ON_raised == bool_true)
			{ 
				exseq_main_region_Inicio(handle);
				enseq_main_region_Llenando_default(handle);
				react(handle, 0);
				transitioned_after = 0;
			} 
		}
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.T_valvula = bool_false;
		handle->iface.M_cinta = bool_false;
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Movimiento_react(Embotelladora* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Movimiento. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorG_ON_raised == bool_true)
		{ 
			exseq_main_region_Movimiento(handle);
			enseq_main_region_Llenando_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.T_valvula = bool_false;
		handle->iface.M_cinta = bool_true;
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Llenando_react(Embotelladora* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Llenando. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorC_ON_raised == bool_true)
		{ 
			exseq_main_region_Llenando(handle);
			enseq_main_region_Retirar_Botella_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.T_valvula = bool_true;
		handle->iface.M_cinta = bool_false;
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}

static sc_integer main_region_Retirar_Botella_react(Embotelladora* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Retirar Botella. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.sensorG_OFF_raised == bool_true)
		{ 
			exseq_main_region_Retirar_Botella(handle);
			enseq_main_region_Movimiento_default(handle);
			react(handle, 0);
			transitioned_after = 0;
		} 
	} /* If no transition was taken then execute local reactions */
	if ((transitioned_after) == (transitioned_before))
	{ 
		handle->iface.T_valvula = bool_false;
		handle->iface.M_cinta = bool_true;
		transitioned_after = react(handle, transitioned_before);
	} return transitioned_after;
}




static void embotelladora_eventqueue_init(embotelladora_eventqueue * eq, embotelladora_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer embotelladora_eventqueue_size(embotelladora_eventqueue * eq)
{
	return eq->size;
}

static embotelladora_event embotelladora_eventqueue_pop(embotelladora_eventqueue * eq)
{
	embotelladora_event event;
	if(embotelladora_eventqueue_size(eq) <= 0) {
		embotelladora_event_init(&event, Embotelladora_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean embotelladora_eventqueue_push(embotelladora_eventqueue * eq, embotelladora_event ev)
{
	if(embotelladora_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void embotelladora_event_init(embotelladora_event * ev, EmbotelladoraEventID name)
{
	ev->name = name;
}

static void embotelladora_add_event_to_queue(embotelladora_eventqueue * eq, EmbotelladoraEventID name)
{
	embotelladora_event event;
	embotelladora_event_init(&event, name);
	embotelladora_eventqueue_push(eq, event);
}

static void embotelladora_dispatch_event(Embotelladora* handle, const embotelladora_event * event) {
	switch(event->name) {
		case Embotelladora_sensorG_ON:
		{
			handle->iface.sensorG_ON_raised = bool_true;
			break;
		}
		case Embotelladora_sensorG_OFF:
		{
			handle->iface.sensorG_OFF_raised = bool_true;
			break;
		}
		case Embotelladora_sensorC_ON:
		{
			handle->iface.sensorC_ON_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static embotelladora_event embotelladora_get_next_event(Embotelladora* handle)
{
	embotelladora_event next_event;
	embotelladora_event_init(&next_event, Embotelladora_invalid_event);
	if(embotelladora_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = embotelladora_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void embotelladora_dispatch_next_event(Embotelladora* handle)
{
	embotelladora_event nextEvent;
	nextEvent = embotelladora_get_next_event(handle);
	embotelladora_dispatch_event(handle, &nextEvent);
}
